### ISSUE TITLE
0.3.0 not properly released?

### ISSUE THREAD

**Issue by jcaesar** [wasmerio/wasmer-java#52]
The [folder on bintray](https://dl.bintray.com/wasmer/wasmer-jni/org/wasmer/wasmer-jni-amd64-linux/0.3.0/) appears to be empty even though the github action for the upload reported [success](https://github.com/wasmerio/wasmer-java/runs/1652772119?check_suite_focus=true).

**Comment by Hywan** [comment]
Thanks for the report. We will take a look at it.

**Comment by Hywan** [comment]
Problem resolved, https://bintray.com/beta/#/wasmer/wasmer-jni/wasmer-jni?tab=overview. Thank you very much for raising the issue!
