### ISSUE TITLE
Compile wasm to Java bytecode

### ISSUE THREAD

**Issue by pavolloffay** [wasmerio/wasmer-java#54]
### Motivation

I would like to compile wasm into Java bytecode and run the code directly in JVM. 

### Proposed solution

https://github.com/hypertrace/javaagent/pull/241

### Alternatives

https://github.com/hypertrace/javaagent/pull/241 does not seem to be complete and fails to compile some files e.g. issue https://github.com/cretz/asmble/issues/34 

### Additional context

None

**Comment by Hywan** [comment]
Hello,

I'm not the author of hypertrace/javaagent, so I can't help on that front. cretz/asmble seems to be a good fit for your needs.
The goal of `wasmer-java` is to compile and to execute Wasm inside Java, not to compile Wasm to Java bytecode.

I'm closing the issue :-). Feel free to reopen if you have any questions.

**Comment by pavolloffay** [comment]
thx for the response, just for completeness the cretz/asmble is buggy and does work for simple use-cases.
