### ISSUE TITLE
 failed for task ':buildRust'

### ISSUE THREAD

**Issue by vanolincikus** [wasmerio/wasmer-java#62]
## Summary
I try to run a wasm jni program in InteliJ on macOS , but I didn't make a success .

## It fails with : 
````
Execution failed for task ':buildRust'.
> Process 'command 'make'' finished with non-zero exit value 2
````
### debug options says this:
````
make: *** [build-rust-amd64-darwin] Error 1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildRust'.
> Process 'command 'make'' finished with non-zero exit value 2

````

**Comment by Hywan** [comment]
Hello,

Do you have some details about what failed exactly? I can't help with that few information :-).

**Comment by vanolincikus** [comment]
Turned out to be a problem on my computer. Sorry :)

**Comment by Hywan** [comment]
No worry :-). Thank you for using `wasmer-java`. If there is anything I can do to help, please ping me.
